name: 'biblio'

services:
  web:
    build: .
    container_name: biblio
    volumes:
      - ./:/var/www/html/
      - '/var/www/html/vendor' # Prevents first volume from overwriting vendor directory.
    ports:
      - '8000:80'
